### ISSUE TITLE
Multiple store

### ISSUE THREAD

**Issue by linonetwo** [sinanbekar/webext-zustand#1]
Is it possible? 

```ts
import { preferenceStoreReadyPromise } from './preferences/store';
import { serverStoreReadyPromise } from './server';

export const storeReadyPromise = Promise.all([
  serverStoreReadyPromise,
  preferenceStoreReadyPromise,
]);
```

when I do this, I get `Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by linonetwo** [comment]
This works, seems each one of them resolved, the listener is removed

```ts
export const storeReadyPromise = Promise.race([
  serverStoreReadyPromise,
  preferenceStoreReadyPromise,
]);

```

**Comment by sinanbekar** [comment]
Thanks for reaching out. Currently, it can/should support multiple stores with [`getStoreId`](https://github.com/sinanbekar/webext-zustand/blob/695c484913ffae4845161e1699196fa804e6a6e1/src/index.ts#L118). If you have other issues, please provide a minimal reproduction repo and I will take a look.

**Comment by linonetwo** [comment]
Yes, it is working now.
